import java.awt.List;
import java.io.*;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.io.FileWriter;
import java.text.SimpleDateFormat;

public class TestUrl {
	protected static String getScore(String appUrl){
		String score = "";
		try {
			URL url = new URL(appUrl);
			URLConnection yc = url.openConnection();
			// �ϥ�bufferedreaderŪ��Ӻ��}�^�Ǫ���T�AinputstreamReader�i�H�Ninputstream�নŪ�J�ܦ��@��reader�A�M�ᵹbufferedReader���ӿ�X��
			BufferedReader in = new BufferedReader(new InputStreamReader(
					yc.getInputStream()));
			// first use a Scanner to get each line
			String input = "";
			while ((input = in.readLine()).contains("cnt:")) {
				score = input.substring(5);
			}
			in.close();
		} 	catch (MalformedURLException e) {
		} 	catch (IOException e) {
		} finally {
		}
		return score;
	}
	public static void main(String[] args) throws FileNotFoundException {
		try  {
			Date date = new Date();
		    SimpleDateFormat bartDateFormat = new SimpleDateFormat("yyyyMMdd");       
		    String today = bartDateFormat.format(date);       
		    String fileName = today+".csv";
		    System.out.println(fileName); //�o�� 20100625
		    
			FileWriter fw = new FileWriter(fileName);
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=hotspring-settv"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=3hot"));
			fw.write("\n");
			fw.write("\n");
//			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=women30-ISET"));
//			fw.write("\n");
//			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=women30"));
//			fw.write("\n");
//			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-rail-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-m01"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-apktw"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-4droid"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-pix"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-eb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-ptt"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-kiiQ"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-web"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-viedo"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-guruandroid"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-guruios"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-tgsios"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-tgsandroid"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-mfans"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-tsms"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=rail-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-bike-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=bike-m01"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=bike-eb"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=bike-bbs"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=bike-google"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=bike-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=bike-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=bike-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=fb-taxi-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=m01-taxi-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=taxi-eb"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=taxi-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=taxi-vedio"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=taxi-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=taxi-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-eb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-m01"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-pix"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-ptt"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=krt-womem30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=fb-spd-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=m01-spd-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-web"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-eb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-kiiQ"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-bbs"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=fb-promo-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=m01-promo-1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-85c"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-kiiQ"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-bbs"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=promo-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=fb-love-1"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=love-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=lovedu-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=lovedu-ptt"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=love-bscard"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=loveweb-happycloud"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=love-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=love-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-kiiQ"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-m01"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-bbs"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-web"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-bear"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-news"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-guru"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-tsms"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-tgsios"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-tgsandroid"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zcbear-mplus"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-17life"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=draw-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=draw-hyxen"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=368-eb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=368-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=368-hyxen"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=wifi-eb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=wifi-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=wifi-kiiQ"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=wifi-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=wifi-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=wifi-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=dept-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=dept-hyxen"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=geome-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=geome-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=geome-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=icare-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=icare-hotspring"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=icare-women30"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=atomic-hyxen"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=atomic-dm"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=taipei-hyxen"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=spd-ios-hyxen"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=drilog-hyxen"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=mobile-hyxen"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=mc-event"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db="));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=funtrip-event"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-funtripevent"));
			fw.write("\n");
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-dm-loc1"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-email-appguru"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-email-bnext"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-email"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-email-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-fb"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zcipad-fans"));
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=zc-web-loc1"));
			fw.write("\n");
			fw.write("\n");
			fw.write(TestUrl.getScore("http://s.ad-locus.com/detail.php?db=adlocus-bscard"));
			fw.write("\n");
			fw.flush();
			fw.close();
			System.out.println("Done"); 
         }catch (IOException e) {
             e.printStackTrace();
         }
	}
}
